"""empty message

Revision ID: 15b0a3afee26
Revises: 1b9d2248e0f5
Create Date: 2025-05-10 18:26:38.882462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b0a3afee26'
down_revision = '1b9d2248e0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=256), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.drop_column('message')

    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=512), nullable=True))

    # ### end Alembic commands ###
