"""added sharedresult message field

Revision ID: 1b9d2248e0f5
Revises: c9140a190c6c
Create Date: 2025-05-10 18:17:55.999257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9d2248e0f5'
down_revision = 'c9140a190c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
