"""changed passwordHash length, added autoincrement to ids, added field for frequency array

Revision ID: c9140a190c6c
Revises: f15c08dd5bc8
Create Date: 2025-05-05 14:59:48.781173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9140a190c6c'
down_revision = 'f15c08dd5bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencyArray', sa.JSON(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('passwordHash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('passwordHash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_column('frequencyArray')

    # ### end Alembic commands ###
