"""initial migration

Revision ID: f15c08dd5bc8
Revises: 
Create Date: 2025-05-01 20:27:37.841946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15c08dd5bc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('passwordHash', sa.String(length=128), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(length=256), nullable=False),
    sa.Column('clipLength', sa.Float(), nullable=False),
    sa.Column('maxLevel', sa.Float(), nullable=False),
    sa.Column('highestFrequency', sa.Float(), nullable=False),
    sa.Column('lowestFrequency', sa.Float(), nullable=False),
    sa.Column('fundamentalFrequency', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_result_id'), ['id'], unique=False)

    op.create_table('shared_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysisId', sa.Integer(), nullable=False),
    sa.Column('fromUser', sa.Integer(), nullable=False),
    sa.Column('toUser', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysisId'], ['analysis_result.id'], ),
    sa.ForeignKeyConstraint(['fromUser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['toUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_results_id'))

    op.drop_table('shared_results')
    with op.batch_alter_table('analysis_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_result_id'))

    op.drop_table('analysis_result')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
